ingress:
    enabled: ENC[AES256_GCM,data:dgDkCQ==,iv:Wu2hA9+k3zBbWrmcDg4alXvO7OGsRYcMrtJLsXNFGGI=,tag:2ehVnB3fsyA3qBm13aUbgA==,type:bool]
    ingressClassName: ENC[AES256_GCM,data:OShtdsc=,iv:YYCcbpEBHDLcVNthkt19U/K5P+jycFVK8g32HlC0rrc=,tag:WA/se5AGiogPclZF8kzAWg==,type:str]
    annotations:
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:ea2R80P+UeDEpOO+fhpSRw==,iv:+GrlrsxpQZ6U30L7EtHYt05rjw/iyK7+joLyJofRmok=,tag:H3H9ibImN8OMXkTETigzzw==,type:str]
    labels: {}
    tls:
        - hosts:
            - ENC[AES256_GCM,data:L6ny6efX+4p81h90Ofg=,iv:iKzzYmkD35ep6bHRDr+XpHjayZLNWo8WKBKXLIPopT0=,tag:IVCh8y2OjqOjOq0VQVMXuA==,type:str]
          secretName: ENC[AES256_GCM,data:zesBt+mWd6/iwf3H9Aa0isFk,iv:XrRr4HNkivryKgZ/OdfV5zhvLMG1/WED+9vqpT1uqHc=,tag:WL4Vyzyxvd7I9JZtjb9Wzg==,type:str]
    hostname: ENC[AES256_GCM,data:/rCbeL0jekSotMW1/Xo=,iv:2a1PJll7YwDsdT+wX5HrBehL82mdpCrAvOIFHz+mvdg=,tag:XBcU0JjLjBBEcY2XwdvZ5w==,type:str]
env:
    APP_ENV: ENC[AES256_GCM,data:LxFSCaeQHz8jeg==,iv:MDRMf5xiSzKMLaN5qnOYk0Aia6iGpaAfVuNlaxTQG3k=,tag:Al+aruTITUygTImUUYM7zA==,type:str]
    APP_HOSTNAME: ENC[AES256_GCM,data:/ew+GfDOWK5xS7e99Lw=,iv:voA7vyFQ5pDGMnAqfmR8+uW3SdZzNWezuIBlzUJ+XOs=,tag:vKc00JpoNQ31Xbmva2tY1Q==,type:str]
    APOLLO_URI: ENC[AES256_GCM,data:f6Ub2Ibhd9n3eNexsA==,iv:P9c0G2EZ2LR7Br94wz3wqXEyyHAk18nMdsCc9JOR7PU=,tag:ULRxa6bKj0rQwUh2luRrzw==,type:str]
    APOLLO_BACKEND_URI: ENC[AES256_GCM,data:27Na0VXVNDmulNUdJAzy4+ggarpUId+fawGYgHCfbgZiP/rABe/VetKjnVajrBFDllktf4Ei,iv:zkbP/5nMhcHt6qcEd7sjJWlIpDeQcgVZBsY30KZj21g=,tag:mNgy+J+idw+KpA7mKljQ+w==,type:str]
    DATABASE_HOST: ENC[AES256_GCM,data:hXVD8oGL5cm5upV+g+fBHk4bwcVQ,iv:buPwDVwdPDzhTsw0nCYlRw7Dzk/q0TWrmst3sSZK280=,tag:EdtFKZsBrJFk8hR0sDjU+Q==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:+7h24gPw9wibXw==,iv:2Bmz0fAc35AnLNYErHOyzHuo+zQgnQc7n1ijUH8VIUs=,tag:1vS0Iy8Rf7UByPfBKSCK2w==,type:str]
    DATABASE_NAME: ENC[AES256_GCM,data:mjmVAGt3S6c6GQ==,iv:rTa7K8dLtOImHQ3JtbmrVxROOd7ELJQMjvLsKnQKyCM=,tag:ZuKfwwmdmOzP/K1889uGZA==,type:str]
    DATABASE_USER: ENC[AES256_GCM,data:z/WZRbUOkMw=,iv:toT8eEwNDePpUGDbZs9g3sP9wIBwQHkUHJCHs53kwbw=,tag:23Ea31dBOVYRzNXZQfAZbQ==,type:str]
    NEXT_PUBLIC_URL: ENC[AES256_GCM,data:PzGMCasds0W6vdqMu5jF/frvwYTAxw==,iv:0JPM+IdnhE8Jf59SgYjGE+c67rCbXoJfyXsbI9MNbYU=,tag:fWbA3j4lFCMNlveAfUB/AQ==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:B4cee6/0rEgY0QgD1zn9fmZzCZicbYiRyciT3xud4Ok=,iv:6Ucap8h/4qOdDU5I0R/SZVe5BO4caev01m7+N4G7ooY=,tag:ss9ds5RCcxbG1cgQz4u7AQ==,type:str]
    SERVER_EMAIL: ENC[AES256_GCM,data:qQEo4ziSlxwQueaNMCbzyW8+/xyVkA==,iv:zpOxiNgv/g3zOJNCyXszDoRZj8RtGMUCVFG0Jym+tG0=,tag:xwBlmnVgJ4j7PZa+A2w90Q==,type:str]
    SENTRY_BACKEND_URL: ""
    OPENAI_API_KEY: ENC[AES256_GCM,data:hO28LIxkXgXvATuTSw2JNBO7J/OEk5zxyTIuLVzdLCw0+HGVni1I5f5YpkyvCcQyskLz,iv:mVE3eVbbDSKzLppiIVxsTrY2lO+cK6smXRVTIndkYLE=,tag:bgbPOyW/YMeuB2be6Uy5Cw==,type:str]
    IMAGINE_TOKEN: ENC[AES256_GCM,data:EzeJVjkmLQhWy62ghPlVVZmwLhUZHG/nvKY7fms3bOs=,iv:01ytqdBiuMGMlNqVgW0zrpCtDilAwT1nDbC5sykOXnI=,tag:CMUIhey1omB6P5XEHcO2TQ==,type:str]
    QUICKNODE_KEY: ENC[AES256_GCM,data:1Waa+Ba/mLm/ErRUBvhbh3Lq/DcpRD+cpNdff4Q4cps0KqE=,iv:366NSz45oAg1/8E8PVlJ0/Ph7bDV6uFsudHx3SUav64=,tag:XHkOif7j0KGEL826WJjpsw==,type:str]
    NEYNAR_API_KEY: ENC[AES256_GCM,data:rsEPypa2xN9uvSDlyZs66YeQ9LiehFwgzjg6ySVXQAFBRKMw,iv:e/u+TkJqTMDt/CDSaTJvASvWWpqjQqdqbUcQCKO9Klg=,tag:IfDJn1+BL6t3m/72t69SPA==,type:str]
    BASE_MAINNET_RPC: ENC[AES256_GCM,data:05+jO+nnW4Hm4w4LyUUrmAKhUIUFbyPWfgi2CnchrafAnWNAC2mDApq3junoPFSLCwO3JKAmxYLBpvAZqFIOccLiLA4uSp0P81gVsvRGDCtildE2Jnx/RJ9xoyVKrGwsrEDNEl8=,iv:7kMDxdeQzpz9sn5bNBudbOngQpeS2DZA7a7GFp3CJHw=,tag:5XmNNGGXl956Njf2Ao0p1A==,type:str]
    ETHERSCAN_API_KEY: ENC[AES256_GCM,data:HKiY806mNBblcWIf9is9cQV/f6MIXIG7tVOFxCrskmICeA==,iv:l4koanX8pKtwLet1e1MwzCyx0pioT6N5mEljKaqdoH0=,tag:NhUhZsXx35TG83Qvrd/k8Q==,type:str]
    PINATA_KEY: ENC[AES256_GCM,data:8XDOd50ETw94jelnW23/nmaRLFApbCBwiXG+hDG4GbNblyd9lmwrpBW62GD9JEaPK6z7lXmtgTVxsqazQDOdVX49NimM6k/TevaU4wpKMkICgsG8joU4/jcXu7sXcxmEYS5VS8czNv0N2iji+2a91Uli7QZSK5VpCWrDir18ruRYCdZY2B5oe/rwu/fgVfET5qwGk3RYSO3DgC+trzObFWoZ9JOmvdSOKBB5TLAo/2+WDJSzl9pFFD2d3yu+qjuX+mwxOmFiN2VWZjs+sCFsrO2362bUAABvN5aHIOmMml3SZxNEf8yAkZFA2dhDeTaTwo5juXu20VllCqtiQGmdo90eHVINSrmul3YFp6Cm7Iiawy1VEr5v6QpCfomRnl0q4HNoAPncm18rohYOxTmI5VGRc0Sjnx7wIxByiXH+gBnZoaHFu1jB6u3zmdqVwWpkemXycgxAI7Uciw2kJSLRjeeLJsxc0MqWVXhWNSNV6Q/d1N5C/j8qXPYu1Cy0kyv/hLAy9dhsr5Esa4fZZvnPfoKZ/cLX5yP4d9z9RDQY60wYqZIJv3NmQ9GWzufspgF2gsKqjt614d+d08fEBKlSPYJwpFQYznycoVB7lv+KQI7hoE0/FGJQKTqf6USxipKOstKf/uZVkJzgOAkCkKTqk+psGggC8rt/RppV8BIDvsCbSDakaKRAOD017Nu24rJp2i5WAvE/CA8RfYXeorjagxPt2JsM12i6GsVsRLO56J8dC9yGmH+d0PT95+ZaF7K1+p8w3Cm1tAIa+y3cCirRSX/s1zG63PgzTFpQxeX2+Gpl+Vg82Ow7rn9TYia1QI4N/PskiDGCGoUsXESAsQmNbl7Do7nYGRU3/igYw6oqxUUmvzWL+m8kDqR9Vr89+KWBcVq1voyZfDkWqPDD9w==,iv:OTTWG3+6ncyCXCZeY62GPmeCtVupIP+0oJnp+LhOR3g=,tag:UMb1BFCMZXG+e2n6dMhXmg==,type:str]
    BASESCAN_API_KEY: ENC[AES256_GCM,data:ew0k2lbzZQhaZlQm0yWIqdp5x+Ki+ne3ExlxokA3xBw1Xg==,iv:Gmiic8mf3BsKx8X62rokYydDMB9EjCFGzi8KJOuyKrU=,tag:1u/L122YEGVNcZcX1o4uww==,type:str]
    NEXT_PUBLIC_CHAIN_NAME: ENC[AES256_GCM,data:F/U1qiJaE8FARmQa,iv:JTcSmNFkJTzhbji41YHZO1KbqG91ISrJR/roIMcbS2Y=,tag:9sHssapF2idqYsdSN1AcHw==,type:str]
    VECTORIZER_API_KEY: ENC[AES256_GCM,data:x8NnUt3NkgiwkOSNTh/2CJ46xdCFe2txqNZKHiZ131lf4xM2Eewn32Hhgn9iCopFNU3h/8ShwLr4VnKXKs4xMd+fkc0=,iv:TabsI2fv0t1J6df368iAQT+mNy/ck7MPbQhR+moNQIc=,tag:Nzz7zyP79xXBaaLhU35Ypw==,type:str]
readinessProbe:
    enabled: ENC[AES256_GCM,data:YeD7Gw==,iv:Y5wBo4h4yo0scYvbINbPPvZxDhag/vOhQJpuaE9sa+A=,tag:HzCSfJXO2qfsvPOBzLCzhQ==,type:bool]
livenessProbe:
    enabled: ENC[AES256_GCM,data:3iquUA==,iv:qbZC34hjbBPF5O4P9Z0ltfaDT0OA6MxEG9Dzf8T2dvU=,tag:v9HcD59j4FtiZZbppez+fA==,type:bool]
minio:
    resources:
        requests:
            memory: ENC[AES256_GCM,data:F9wcc0M=,iv:Q45d/zRTQwZH6wVnybb9AO89pjOrBPYapCk4CouoU3c=,tag:WKMeM+kCXBvv2ZFoSAAQeA==,type:str]
            cpu: ENC[AES256_GCM,data:MjnLjw==,iv:GSDg7FCiSUOtr90d66HHiO0gJK3ZH3Kdgo6r8MgiPto=,tag:/sriVjvjU9XPXQ+b8Zz93g==,type:str]
        limits:
            memory: ENC[AES256_GCM,data:BgVz,iv:8Zhpau3iUUtHI+86/j0AIFijVEnrdx7z2kOlH4GHNdU=,tag:nsVR18hfF/yJafoFPPbB+A==,type:str]
            cpu: ENC[AES256_GCM,data:l1BT6bc=,iv:SbWDE1zDjQwMsQYevkvAyNME7bdHsDaVG5FQZTjX73Y=,tag:s9kYS3WzYDec9ycqvJGPnw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t52j4y9qq32qnemahzvthge23mayrcfy3cjw9a8mrcw940vt6das0alrkz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dUJpcS9ueGk3OFZncXh0
            clhsQWZhZ0hDZy91b0cvZTBZRzFGM2dtVXdBCm9GK2UzTXhmKzczNDhNYnZSYzJj
            blpucXB3dnNQejkwem9qYndDRmRqMWcKLS0tIEJvVzVncjlRWEhmbTBCMGhQS0h2
            emxoRDIzamxBRFRPRVdGMjFVaDhRZWcKpDq/7ZnJ92HBxxVz8IcgAvUOwIe3T3zw
            gDJ+M414+An3lmtYqJmDlnRwQDirGZfjfUpyNDx0KbiOTWZrKmPgiQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1d8d79vsrf9h0avg3dwjl8fxsx3knzhvtg0ykf4k8w539878ql5zs53q6pj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dTR5NVJvdVdNaHNCN3hO
            YVFyczF6Q3lZMWtYaDlXZTFwMWhUemYyRDFjCnlyL0o0dlhMQktMMVBWZU9rRkFY
            MkNqbVFrY29hcGJvL0tGQk5COHhnVGcKLS0tIDRPUFB6NHlnV3VmT3pWcUk0Rng2
            UVZocTkvUTE1eUJnUlhZd3QzUzMrQWsKSQzHa+0pb5E593Yd0OFCVVSDnYCdSIK/
            cik8f5mB/ZS1qLi3ISOpjQAEbLIbra1RrXroWje78VElvTQkcmQSlw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1a9fr72jum5ysrpfyw7z9fcp9dgfztd5wskmu4erj6e526ul334dq8clzec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2czdXbTBXNmRYK0hVNit5
            NEdSOWNtZnIrSGtSdnJiZ2JoSjlNZ1hyWEFrCmFicnpKQkpjY3pydGhrZUVkK0sr
            bUd4dHFSd0xwU2JHWVg2YkR2bzA0SUUKLS0tICtLUkt0WUJsTFIzU0tQcHlKMnV6
            bFoxZGhrY21qTjl5eExkMkZFc2JQSmsKqKuF8dtaBGJxujuCBko7WlT2rLpwTAfn
            bD/Higzw54F5CdhjUqCwSdrx3UpdV0Q0Qg6Q2WabtgTN8fKImh1BgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-22T23:39:35Z"
    mac: ENC[AES256_GCM,data:BbdKc4y7r+rqbQFR0RaXQqwOIlGDcY/fTh8RV1sdi6I5sDAMwVradRZpeik3vileJA88VMBFFOFUUrPpf6MuP9D4EF+/T9qqbmAgDurRQfMnh+Y7gFYz68LcZYnD8KZwzKtZ0vZUdcr0UNBg+X4kZSHz+h3RVYfAY+nCbcovzzk=,iv:gbsQM6GflcBrPx/NF6LKdhhtIFceSW74UuS5isztgEI=,tag:/ZgYJ8TkexOiuK9bUlA3fA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
