ingress:
    enabled: ENC[AES256_GCM,data:6wfXlQ==,iv:t6dXesDEmasNcKPHvRyeSd6JLkRPv0IviU/fuGVUzAs=,tag:CJ8FUezYaftMOT9GxyihdA==,type:bool]
    ingressClassName: ENC[AES256_GCM,data:uCKKU8U=,iv:HjHRVXwDxL3D4i3sU+/hLKuH+d1XcpR3KQZTNYXaxaU=,tag:+uCiZlf0rqrhkRExGiafnQ==,type:str]
    annotations:
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:dHw9qjgZl99pPPYbngnzzg==,iv:pJDJmA0KoCV63T/J3QHi9E02Bn76+8V3+4VyJ7k4wI0=,tag:UKuZtbISAIA53nAL+cfdvg==,type:str]
    labels: {}
    tls:
        - hosts:
            - ENC[AES256_GCM,data:xVH0xw+ENFpSE7hLhCw=,iv:Bx78mPTlvlLxlfeScx4nsxr9lqF+AqyF2if94XmjalM=,tag:vtRUzHgpzwftmeGh2oUewQ==,type:str]
          secretName: ENC[AES256_GCM,data:ujL6vwUSfWcUnGBdSibB6cs3,iv:AIH4uH/GEZr9SL5blxfWok6EiT4jndad7zIvOk7hxOw=,tag:biBMZU8A9/4umbFy2wFmYw==,type:str]
    hostname: ENC[AES256_GCM,data:L13MD85B2EAP7sO+p0s=,iv:hJ+alh4DdLVeenzd1KXkqCUUxNBThuhL9Yly2MGp7Oo=,tag:ZcpOckFZNojfqsZ804oa5Q==,type:str]
env:
    APP_ENV: ENC[AES256_GCM,data:cPJtEwgioS9RRg==,iv:MTOBlF+obXnG48c4TMEisbI6yQh/5hUat+5DbU7+zZk=,tag:cZKQPCvodnponIQTq3hGCg==,type:str]
    APP_HOSTNAME: ENC[AES256_GCM,data:L0+LfPxHCH8NSihjvyw=,iv:1q219zbA7ywpbJykQtAV5PKcmcInU1MVuAdqiYBMPdQ=,tag:eIUGReVocfBAzsgW3QGJ6Q==,type:str]
    APOLLO_URI: ENC[AES256_GCM,data:ZqSbx/lXVZfelxGenw==,iv:XS/9xc6femCX/ppP4xlToSVTNqRn3noUfeGAN1j7tJQ=,tag:Ja5+tpYR7XoIuuZ41EsNvQ==,type:str]
    APOLLO_BACKEND_URI: ENC[AES256_GCM,data:vLgCLdEFFtynRoyIsjiCj5IqJfncctBMpBfMIvT3WKjY6o9WFtiikjn4Ag==,iv:ZGopRFNEiLs5cfdK9gj6YfOiX3vjJSIanv4RCBKzDj0=,tag:4pATwNoLFIDRDV03JupaOA==,type:str]
    DATABASE_HOST: ENC[AES256_GCM,data:1r0JBeFRy+3mBeVUMWTOq4otasN/,iv:g15K4hK4uQjhfa1HCFGPdLR0V/+Wf8Ms8o/cIh/AYXE=,tag:dTas8ZtzsnfmGMoCjJPERQ==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:QPys+ZFJ0GeMpg==,iv:Cwn5edD+Yi+M5zIgcNtNH1Ky58yCyzCklyCzqxWblHQ=,tag:mhYpO0wHzwgRARnbLWg1/g==,type:str]
    DATABASE_NAME: ENC[AES256_GCM,data:YqIXRRoJUo88MQ==,iv:RV1h4QtZsvO3cJ1lmM/2YkhzCQDP2AXDHkexCJDRjdM=,tag:HCHhD0PSURYfxLrNLN0uJw==,type:str]
    DATABASE_USER: ENC[AES256_GCM,data:Hlzn7RDhsrI=,iv:gnp5sktpgxWRb+F7WBg2CuShoW7icfaqwSkGr2tvxmc=,tag:Vz4OrSMslko1Qz8bKvJN4g==,type:str]
    NEXT_PUBLIC_URL: ENC[AES256_GCM,data:q3kFldyMYiymPzc+HltK1++GHrBamg==,iv:ZvAxnYjoMKbTgsljVGdj9wcm3CXn5yFizLxwJKGtnX8=,tag:zfUkIlYO0rsCaLof5XjIfA==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:0F5NOe3+ykaNfYYkek7YGKnGxXwPUk558MlNcSg1m+U=,iv:59OkHwy8G82Nd5j3ytc1BSwIJcNCHigyGmu3PoK5iE0=,tag:m4lPDPvvuISgYX7yId86lw==,type:str]
    SERVER_EMAIL: ENC[AES256_GCM,data:PFyaCb4YtR5GXE/aPYjSVsfqc4Cgug==,iv:bz71eKFrzCFQnfZtaZeDbGTmMQvB9dzTHAdxoNnRMWA=,tag:J8UXkY0yCSVxANhp85FVlg==,type:str]
    SENTRY_BACKEND_URL: ""
    OPENAI_API_KEY: ENC[AES256_GCM,data:GD+VtRx5S5m9+K67GWJAEItr5vOPURK3IpmjZaME/Dx3yxVvKAOaOXuVgufmYK502qng,iv:GNebyZHBpxhGSONnnFWDRtW+rm/aLhU+tFnxWiOVQk0=,tag:m/PeRceXJg52auGwHBU6bA==,type:str]
    IMAGINE_TOKEN: ENC[AES256_GCM,data:u+QBpLy79GgYxm0tPi+8vMHZBxPHzcLhBFwMmFUSH6I=,iv:0GIACCTOW+OW2BvpNuGmKbqNqrX22PQVTtWi15WOipM=,tag:X15aVv+uYy0lTKPiHQKm7Q==,type:str]
    QUICKNODE_KEY: ENC[AES256_GCM,data:VmkXS1HNp8zWr6P/z+WrQAnbD3MM/jm4HRz9mL7pC6DcLCU=,iv:vjSSORLo7lC4co6R/BgnyQaFstW6gl0TWKotULSvPSY=,tag:jpZY24mnhmFu4Dg1j1YfCA==,type:str]
    NEYNAR_API_KEY: ENC[AES256_GCM,data:KTIuLiBYSRKIbRSWS7bAtZtsrTM9Xumz56ODufRSEc8ylrXI,iv:yoFX3gVNUKaYPum9Cgd36vBFa3yq+XNj5dE62BpC6go=,tag:IPmAJfqAax8HPTeFq9Gb4A==,type:str]
    BASE_MAINNET_RPC: ENC[AES256_GCM,data:POkNiTR7xDCiiRJE/bpckllr3VFdCwO92W/eMTX6miVANa2l8CIOePbM7NIHsDB+DxpsTjlkGAIPM+M+LK/wdDv4WR7+YYuq7edu8y9kU1r6+7bp0OGRzNj+cxkSDMRReUs5odY=,iv:THpKBcIG66FCFHNv1R3oxsUdyMWm80Q9uuh5bX1Obvk=,tag:Mki9sBJ59fzE2xdJcrHtUg==,type:str]
    ETHERSCAN_API_KEY: ENC[AES256_GCM,data:fx13Ac6hFNCEUj2z6/a1y+EjpOPJbCJuyYWtQDybtjkfzA==,iv:SNwmJNwWDu+h1U00A7sGNxNppgEVh3zXFW403ynjZ8o=,tag:Sn5lIkIdClVXPcbKSfHhag==,type:str]
    PINATA_KEY: ENC[AES256_GCM,data:uoOcgiSW1Aqk/X1MpR/GdaHIoedmg+xSwZwqbd6paP9gvocaAjslWC1bKtGsM5vYWbuH/8r0c1da4oHYBYuxMB9xI6V+rEH/WMjXf/PU1dRuIkru5GapyQNXkjh2PUL3koujXb23rLOWEQDNQ0u1BQxBWDmJSl1XpWZGBRv6eK6rTpDdjM7dqd3vJZTVET4a+6ReIN4Po3G9+tk3exODF6OrcSCZXLmS+D3IrVTCx9bQqBfgM5mkCic5SBtFHsFk8vIOuiaidESxaIBJgwHGDgJzGsn5MkOdoxPULVW82g9YYK5sI7+9fic1KdI6bftZiQj5Q9trvPGMSop4n2Iv+yv6ac5YbJ2lJtjcBOvJJ+w3A0bFiqwgmzMZkOmxJuN29HWVpTQZDerAmDleRWjIx6XpetiUytSxsp/b64TjxUvShLR4Y7lhf+CsVx0LkQncb5isttImXliah0d4XeROfEu+Pb4wjJzKvySOjvuDS/Nb7YW00YmrV4SMy4q4cJWFsrHioLnPHcs8GVPjodZJYOi3BkJ5+uXMB4yyJQhe01zc4k6vCiXYgq9g9TpDttUyF9sYrmVFAXualIx5QVrTJtEE7XrBr8Qar2e4bKhjlPSVBgMtXzwxf4GeL5laVZp+bX9HrdWZinYw1lodjByL3dt+wnyKof/adqHPLGLPxoQcmR5Mdr2n8LAfJEeqXvvswReePGqvJ/1HsfUYmWPKYazY8SLXuweEI9BohtEeQ/LW+ySwvt/ubdRHI0c3fu8h41lKfiFo3c6LeVlq3IIOf9aR0wd1uHZ6J3AzRP6SCQeZBMxbWVMoO+yy790tJu0ITSAV1TaVhrtG28GC12MK4jGy/dFSqStjDj+5J0jfa3bqFaq6TYRdx3jAasPYOso15iM1Rm+EGue+JJnYQg==,iv:QMdaHjA4H4yFTGBKe/Gwwx94jhj/KM0WaHpu2WdfKeY=,tag:J+9XF1REi6+UmKJZ3Ep1NQ==,type:str]
    BASESCAN_API_KEY: ENC[AES256_GCM,data:p0tRsfqjVEh7vS1sMF5UBJo5ly0lrmPmVNab2/hUAGrMdQ==,iv:TCdeYFj1yHpxwdbfOD1anFN9KarDLyxENU4V4GwHApY=,tag:8qRQsC9av5O4fy76dcrL0Q==,type:str]
    NEXT_PUBLIC_CHAIN_NAME: ENC[AES256_GCM,data:Wgoog5YhgjoCkc4v,iv:SOp93J6LLFzEFPe2hxJeJXhWj9kZqj5TOKDK1QkFU/k=,tag:5ifChYqdkjs9BhfVPlCGKQ==,type:str]
    VECTORIZER_API_KEY: ENC[AES256_GCM,data:0DO/D9jKjtQHIyDJyfLhMKVMEOVYkx/qsdMqrjaXH+JvXOVGA3fJn0g58WQi9bu53g1FkLPcexvEWzHZAqfT6ngzzY0=,iv:opmikd1b6HQPLlnt9BsDHKgGQgbQdMzMUhsa3EMjKpk=,tag:3Nv2z6zlAbcFNHIDCoN8yg==,type:str]
    ETH_WALLET_KEY: ENC[AES256_GCM,data:9zgFa7y7ucPQFxXI1ZcFENJm8xX9yexS8YQL0XcJkcuPUgNjycZYcBIXWm0PiXiiUPrUYZOb2m3NEkDYTNADZLMJ,iv:8rtNwBx3JkIxiF7MsvkNjTGyWFcackDrzr4enxLtsSM=,tag:BKL1RdS5461MniA0lHM2PQ==,type:str]
    ETH_WALLET_ADDR: ENC[AES256_GCM,data:Zy4XNYx3hp2nqn7+AvkqBjgNIQd6RQXtWD2bhgBKHjLgxLckLeYQtpgN,iv:2lFPB414lc9+k+2EeGfgCPVq0vXL90w9lEntzS+4U1w=,tag:XX2leJsDzNoGknA5Uto7tQ==,type:str]
    NEXT_PUBLIC_BASE_SEPOLIA_NFT_ADDR: ENC[AES256_GCM,data:nTMifYzir131Rz+0CyAhs1fCkuD3dZhe2cYBWQLNMliEyrplWxVA43bl,iv:5ZbKvIctnXJs05O9GJ8LwkT8NJOy1YROXIrhRNcLozo=,tag:hK46+Od+SliyKJRRRASDMQ==,type:str]
    NEXT_PUBLIC_BASE_MAINNET_NFT_ADDR: ENC[AES256_GCM,data:jsHTIk1Pp9ztYJL3VXA3kJML1/VTpiEHGwbD36agDxR6mDfaYgz99uRJ,iv:LROQjBHaTHxiy3AdxIYw6QyD2altOj2XnzhAx5a/yF0=,tag:Sh+ZlKVkYwPM1UOfq7usRg==,type:str]
    NEYNAR_BOT_KEY: ENC[AES256_GCM,data:xFENLYUxDyJU5KSVWUbwyZ5dFDt9GqhvmmoYzvOwIPgeTrd4,iv:eIwQL5nBx5Xk0ayWER4Tl5i2Vvf5QN7jX/61cjZAxko=,tag:JOe9DtkuPISpzYBP32WOMg==,type:str]
readinessProbe:
    enabled: ENC[AES256_GCM,data:EyQOKQ==,iv:hNmR9adPjPhWTVlCCTE9WDNH7+xca3NRiQJxJuZ36W0=,tag:YblG6HPwqxgJFWvAMaW2Mg==,type:bool]
livenessProbe:
    enabled: ENC[AES256_GCM,data:0OHvSA==,iv:7AIqNRpHsWCnDnRf63PsTqQ1jBiPX0eTbqWKIR8sNL0=,tag:MaaOb/jVGEdjcWdTglNnsA==,type:bool]
minio:
    resources:
        requests:
            memory: ENC[AES256_GCM,data:RtLJleY=,iv:zM0HjxsdxKXxBAyH1iIFUu/x/Y5SJEqZK2ZJs3c8XDI=,tag:DjmnmuG6bLCxbYk8+5EQdg==,type:str]
            cpu: ENC[AES256_GCM,data:FZK3/Q==,iv:xXlWO30YtpYzYAej7rxWkPedm6WSqIRPvYpwHMtMhT8=,tag:ESsPhUyHp3hfWVvOqz+USQ==,type:str]
        limits:
            memory: ENC[AES256_GCM,data:dRY1,iv:A5S7iRXetWBJTd6IHUGb+GH4QljYKzz9QXp9WdcTFJ8=,tag:GQPw8m6NR46u/AYs0k68zA==,type:str]
            cpu: ENC[AES256_GCM,data:f5WkkHk=,iv:HehxxGYRefDwXRCIuFKUpfCqoQcFJAlKa+V1CiF2uP8=,tag:lR0lGu86+YbX2868i5OGRg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t52j4y9qq32qnemahzvthge23mayrcfy3cjw9a8mrcw940vt6das0alrkz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVV1c0dnlwVEFFNEV0dmt5
            Z1d4SG05ZmdsUHNwUjRud3R5M3M1eVVjVGhJCnMyWmpOb2xPajIzK0N1YmRSUkcv
            ZUxYdlBCSnhJaEx1MjR6WmNLeFlHMUEKLS0tIHpsWWhoOGdWSiszRzlOYkVCMklG
            MWtHczgyV1I2d3F3ZFBocWVHSENBY0UKvcRJdjrhlHyxYnbjXEknmUtN879dmAhJ
            u5w7y0/1pxKCjghn0Wh/hW18Fr9A/pmJJlV+BERJN6jHYmXU2ONm8g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1d8d79vsrf9h0avg3dwjl8fxsx3knzhvtg0ykf4k8w539878ql5zs53q6pj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNlZMYktLdDBIRERaamc5
            bGt0cEd4S3Z4SDlsWHpmMHMrRTVYUmdlWUQwCjNIdjNoUnllcTgwYmJzYS8vQW9Q
            M2FLL0dqTVFBbDV1R1RVQWhFMVhRdVUKLS0tIHF0Sng5dnpiK2h6Y0YwT3ZvSGVC
            RWE5S3grSkpma3hiOUZ1dlZONTQzTVEK3eD7dTrpFKGhipqQtb66MFwqFx7EUr1b
            6FteLHWQyorEFGBauGWGLGfHUbO++VCzV0uUBN5LbNT+cMlH+58CFw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1a9fr72jum5ysrpfyw7z9fcp9dgfztd5wskmu4erj6e526ul334dq8clzec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZ0dJZDZ2ZkEzT1VZYmRo
            T2s3Slc0V3FOZndiK2szdDFoM1l5dzFXSmdjCkg3TlI0N1g1WHY5ak5KUGxweDBX
            K3RUVVlxc2QzSnF0clVEZkNHREpYTlkKLS0tIG13YWxZN0hqTDdXbmZ1UjltdWdR
            UWRPVTNoU0JZY3U1dGlHSHlld3VPUnMKR80dlNahT3fzgHKfIJvoY+k1IM3lS1+q
            QvVtlmLPIMPVIiw0+zlptPuZkNJ2KLkSmZhqOSPVSYQGuEwRXkkriA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-24T04:30:59Z"
    mac: ENC[AES256_GCM,data:CGYYcrB78t+a/6zPQ0btkQFjRHMe/82GUbq7U67fc4K7/nf7oX7gchlsKr4lO+3KVr/s32YTZowg6oOrray5RoTamZWnAr9QudLIXtPOH7wFDSBnGV3T7sfE49IEFPyvzK4f4qXHFkxlaE8uuSb8kBxYZwmI1q4Vrt5AYGO4C2A=,iv:UlsgK4jg/l6A2d/X3v3wQpk2lSGkfOa79PgtQu47YU4=,tag:5Ish+/Kq2uD1eeXEoZk+qA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
