ingress:
    enabled: ENC[AES256_GCM,data:Q+VLzg==,iv:Ht4lnnpzdXD1XvNIRubWPmt6W1G+eI7ekGLo+RE7BWg=,tag:9UBO1Usi+wUsFa3c6ZpMng==,type:bool]
    ingressClassName: ENC[AES256_GCM,data:F6ueNLA=,iv:TT7ki5Ni+c9UWhhh1nwvf/ya1+ncnZfdWvsfAu98+3o=,tag:8ur/BBGXkBJLNhVARb74RA==,type:str]
    annotations:
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:+9wbR31QM+udGEelfY51Pw==,iv:OV64RMCF7U4UkWxGcqXqS9jnLDElMslpWx+zeHtfO6E=,tag:FMZhr09tgxRw++gYONIKiA==,type:str]
    labels: {}
    tls:
        - hosts:
            - ENC[AES256_GCM,data:NnpCywYPJT+GPSsDNnt5QGU+6eCvjA==,iv:SY/eNZ2Pzceh1/RDKbdw/A80RRhxJCUXUx1TT6YTJ1M=,tag:3L9CpJ5jWoV+JVg2gdCYFA==,type:str]
          secretName: ENC[AES256_GCM,data:Cg6eRMAAzmo8tvCiLrTDiLxxcN3oG6SM5WY=,iv:tURncmwaTsazShIDdutM+kVeAEcIv1IhqRMYcF1mBKQ=,tag:9F+GEo+hAfNEzrMxgcszrg==,type:str]
    hostname: ENC[AES256_GCM,data:vTbvf11QtZ7Cad8nCYRjAdHBXJOK1Q==,iv:9XML/QJ2GkOrMi3hP66lfZrz+vdiXJQFr5MDi5/vRPo=,tag:W2Sc/KSVnMC0TRNLEL/NFA==,type:str]
env:
    APP_ENV: ENC[AES256_GCM,data:IGkl98jvIg==,iv:gmxHNbIFB4E3qiaPYK3S7b0+8y/+f1YN7I1UQDl/LNc=,tag:QtIR7ENKW+3D0lfA03wvhA==,type:str]
    APP_HOSTNAME: ENC[AES256_GCM,data:P/mHJF3IAIo2B3bxzhPNDRnfiAJdzA==,iv:+PoOMvkP01UyHkGYepYvbWOeE0AhZ3DqQFc3o+qYXrQ=,tag:XfvJM7KWj4C5Urmc6DxCRA==,type:str]
    APOLLO_URI: ENC[AES256_GCM,data:7EsW4S7p4zpiYceODA==,iv:e2jezJlwsETtCrypnZ3/K7E6hZl531pd4UhAYm0frj4=,tag:lgYgfgrcIHjOucZ/WRMG7Q==,type:str]
    APOLLO_BACKEND_URI: ENC[AES256_GCM,data:iZ/68KxgMO/R/FWJh2DTGLlF4uSl7FdH/9hOuHsbfxl/daJbJLLEETAlB7hEGG4GI9BhY8mI,iv:tr8cOa0FjAlCZTJATZWe5teI2mhgn61eakMns4W8psM=,tag:1GEeMfWsjdtUIh5m5IVyyw==,type:str]
    DATABASE_HOST: ENC[AES256_GCM,data:J+3O9Kp8Jwf7d6uLlCm8iJxo78iz,iv:XFW1xVewqsqtBkBPwcjT/Rv5YNPS0AK815dMk5H621I=,tag:+DKqIdeIZ7tGB6wnk2YDXA==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:DaQnDrl852h5QQ==,iv:y4M+KN3Dqng8Lmtk0NUPUwG+6ue4QrKBx8ZMdgc9qgc=,tag:n/OO/G8GAI97o4w4gwRmcg==,type:str]
    DATABASE_NAME: ENC[AES256_GCM,data:vpkmrZklZwvf3Q==,iv:2+DR+fZbQGCOBxRCvBUkH54bmMpa2BL3ROFP7eQYv2I=,tag:H+yTlvzjGaWWJuG7Fwfg/g==,type:str]
    DATABASE_USER: ENC[AES256_GCM,data:1JmVyWWVkBc=,iv:xLDs2LrujboFnTL7jQgtryZcf2yrpmdityQYAPAl0p4=,tag:17rpeI6e9BmYdv2a61b/ew==,type:str]
    NEXT_PUBLIC_URL: ENC[AES256_GCM,data:xwx1XCGwWGSseGtScGxkfBjKs+HbzK8wVEcNsFd1,iv:oWiyHrFAspN1a2bXwGV4p3CPOl16VbMilkWzTvBAr9k=,tag:IAl+djJuIO8nXzTPkVezbg==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:7R/aWNsgISJkIS5cAgF4WLJ9jhhawV1Zog9LflWBLnc=,iv:iW/0rK8HcoqKAyDRpoCagQ5/VbEAvnMXjy7foQylEs8=,tag:8wY4FMkZMkdgpviaPStudQ==,type:str]
    SERVER_EMAIL: ENC[AES256_GCM,data:kEiQHKe6imGaoG/xRgF0f+A6l7hBmw==,iv:YhUWcYvmFns4l+zuJhQen5tKRaWmgMvi2vNWNNfu1HQ=,tag:B0hjfbnoJD3BRJaFKAr2gA==,type:str]
    SENTRY_BACKEND_URL: ""
    OPENAI_API_KEY: ENC[AES256_GCM,data:JFdCvIRmpXa//T43PUiCmIciadhs4yp/knltyrHkN9zVtoSt2AKop4DPj5m91q+ciOvO,iv:Yv05OqckKw4QAltFcKXBHfjHPJcaKTTpkqw/jhTWhtE=,tag:ZCzbRt81rvxLFvthp1tZzQ==,type:str]
    IMAGINE_TOKEN: ENC[AES256_GCM,data:NpWHvS1oTlpdX9kb3GLx/N66bhtj0s4kT4fJfl76DvY=,iv:cLtiJ0Bu5HD5FH35RA5BP2rlJlXaxXIW+eXwH0gjnJY=,tag:d/ICQsmgXDCxV/nL1OTGMw==,type:str]
    QUICKNODE_KEY: ENC[AES256_GCM,data:Xi6W32S0lNev51UqjvjiYESrFbzpo6YXtpbcVqKyxZj9o98=,iv:WoUIJ9fqQ4EbjC2N4R7A/fX0Gv9G3gl1mEQFrz1nPnY=,tag:EDRGKw1XpHRte+QXZsDsgw==,type:str]
    NEYNAR_API_KEY: ENC[AES256_GCM,data:5QcivMALhAHjO6bPKFmK/RGRN3Gxmgq9yuSZ2UNDvKsL937Y,iv:fOuVhCjR3jPrGoM2LVb7+3vF9L/hUZPymwWM1hdAaKo=,tag:enQawIo8CmNpnOxtIngFPw==,type:str]
    BASE_MAINNET_RPC: ENC[AES256_GCM,data:eMN72+vgbxrr6GhsMcEqUIUkzVCN7IrLO9TVuzA6OXAYwhbLO2bYdxGn+Icmq+9T4DqAIzVz8bBIYZgyc3tdjh//ZycSQ3Mn5QOdcGB3R2rtjlWEr0sB/7GGaOP4vBH5Ghgj9T4=,iv:AlTdtxGFlxj8IiVfH9Uwp0BPR19+4DDMy87WO2MFlsM=,tag:eV5ibUGF9vjHiZMtsH65eg==,type:str]
    BASE_SEPOLIA_RPC: ENC[AES256_GCM,data:Farn7CFX7MVSp5dcS/VQk8EZ5VuS6XjtlQ==,iv:3ZULY7JzgEX9PtLItVeAe0OZNO8OebPe5e5osXHfiTs=,tag:SOVH/a0yuVIbecAZtsSmdQ==,type:str]
    ETHERSCAN_API_KEY: ENC[AES256_GCM,data:8j5tVQ+g6qR+Msq/DAmyhewC6LHuioz9vHjaT+x+RS8Y2w==,iv:eUCezGXerAWym8AZrjtNzpL4WVkz8xgwPq4zOaHMXRs=,tag:BScSjCz+pKWttshAzzH1HQ==,type:str]
    PINATA_KEY: ENC[AES256_GCM,data:TSqptPxjmct/Sb3jBPj/ozWTvi3AXZRB38NzIhXMsf8eF0ZgsX9Jp0wPNZWJ4POeak4uPipTdbbFg+ZcTtfZgFLIMrcVpXTATeTig/9yEIcns9LxVAOSEyzKSF1PFwigzWha3M2dH3oYIAdS9gBcvof/Wx51TNkHK/YpRjEKn5/bYevL9bh2/F9T8i5y4nBNCWAKfLQMbEnB5GzRLaVLjxXIy2cs3foRqhkE3buiyy+EfiyMHL5qeW+dtdRM2NH7C5jppCPTMOah+8uH6TeV7bRkh+87kNyTlIWqwIQv0itkApZMEI/euHlHkCKJIMEXEg8IlpZ+B9/K72MKXC1CX0h8KZiAMxIII7C0z4uaMMzlNkFFp6zNlYYMM0K7lKNnqM5aG8B8DGO/w89U6/ZHX7ikdYlDLIiBmwFOf7JQLJWJSfvke/ND1nn/28SGEs567Jfe44RbpFDYjlkT05ZbNSsmRJa9MtK5NegeV8WYm/cjypIOqPSnqCBryZmbSWecbRlvDOuL5P5DZ9+Q74cdFsB1wgIzk1ZDdnTh+WTu7ldyk6c8cXyBwFdBlZMrlIkN3Osou322sYSYKNeFn81d1v0mTDifdJDL5yC7y5lRMIFUmDwYGGIaGpHfSZrjeBK7ycDXtfzuC5BWWKL0pmtDp6EVjG5fijbz+/WZIfnWbwE0wKSPNp0Qq2gLkqyMr7z5zDJsgqJEPwJ3x7zOvYiwnMIwL6auQXn49JEkUopDbek1ATXyvYqWx9OgLuhm7ouWElfgNxA5Ct5o57x83IrJOCI1vTBc0uaLkLbpDer88aVUsaJ4Co0AhOOO8U82Ea+0xf+yzJrPQMr7hPikKGPfolkxfHOdS0qBpxRO7oSCUpZqWwpiXvoh4ivCnSMClqh/r1CYffoUcnbnhOgLFQ==,iv:MIRX5oaQ1qvJVl5PFO9uQbMmIdMOVjuC++JHUGj98rU=,tag:BbPXo+vLpqojjceVpDTwwQ==,type:str]
    BASESCAN_API_KEY: ENC[AES256_GCM,data:rwIGXv35fxEr39PwLWruxrxyUuWMZMipWXyKDPI3wEENiQ==,iv:0u8VEiSJSd7Ad/iR50UmxGY9KWxOoxOgOsiCtmoTZFs=,tag:s3ac1fL5mrdRzs1EqyxsOA==,type:str]
    NEXT_PUBLIC_CHAIN_NAME: ENC[AES256_GCM,data:oCt3yj5Qexc98xVV,iv:bJtLRWkt31tafHQWzL5+MDjxHhDL2ZkTCtBXd0ABKAU=,tag:73dB5J6MMI0FEIHRTMsi8w==,type:str]
    VECTORIZER_API_KEY: ENC[AES256_GCM,data:NoXnATDaYvVUCf/xykFfwdPYNrMmoaZtoI2PKYUNfcsefGKO6wmORl07ajnnnYkHdGTSue3WA6JJAvHrUiQB3Ug9U4M=,iv:dfPmO7M1eRDaiBQFwBx9w6VSeJZ+PN776WD/Si0EOto=,tag:oab2uMUTt5kwIYvqI2nu4w==,type:str]
    ETH_WALLET_KEY: ENC[AES256_GCM,data:0sPOjQtMvxEp0vtqGAg8HfxdOjwNvgurytq3HK+IZmp+IhWgh7zTovHWTfEOOi5zjmDMWeyn6lWF8T4s7HJ4x40O,iv:lqKzXih6MMSlaEbkijUqgIWbPv1ayPZSpCDlCbMN0bY=,tag:MJPXAzuNrwg5HnKMpwXH6Q==,type:str]
    ETH_WALLET_ADDR: ENC[AES256_GCM,data:xNl4211Y8rs5eYZL7+OO7uq4TB8fzZBJxHhNvHbQxljdISX8wICqehBa,iv:nwIrTm1se6Z6AHvicMoAAVhxy4EBbAC4+cSY4gGDfSQ=,tag:XlC0qDwuFZtO54KJVh8rPA==,type:str]
    NEXT_PUBLIC_BASE_SEPOLIA_NFT_ADDR: ENC[AES256_GCM,data:X+E/aRQxxA0cth/J3aV46BMS1eC+eUakdQHai6Q2f8hxJkknGvu/KRlh,iv:sd97gmq/kcjfbQwzJm8CszbplDbRFeL0TWkzJxciVVI=,tag:dWBEgVb1mlgJnIlS9KO9wQ==,type:str]
readinessProbe:
    enabled: ENC[AES256_GCM,data:Jtzaag==,iv:SYaCxdsYWNtWB9jpoGX1ap8WVxzN8IGoYqit9m7vEeU=,tag:Kzik5WwrSkju870EduGC3w==,type:bool]
livenessProbe:
    enabled: ENC[AES256_GCM,data:t3tbxA==,iv:n9sYhEtk+4BbMKmducxJFCifOi8HruQYtX/aYuj26PI=,tag:z9BRqrEgOvwJ9ZUaFZZ0+g==,type:bool]
minio:
    resources:
        requests:
            memory: ENC[AES256_GCM,data:ZlsP/Yk=,iv:tbx9vFPn8/3LDr/vp71zoiuV6nqG4JJ2v2b+ynUCj70=,tag:plJrMslj5HOntq0lzlvrVw==,type:str]
            cpu: ENC[AES256_GCM,data:yJFbmg==,iv:o8MEFHFr20ysbwK4o0AY2I2KC1DisxIR1u33X09LYyA=,tag:7hYh3yIz6bjaalU0y2Sagg==,type:str]
        limits:
            memory: ENC[AES256_GCM,data:aVjM,iv:vEM2TiQwBKDraLRIKfvtYiFpEyX/vBks5vCMN/zKFBM=,tag:fguy1xz5SKCczJPAyWO/qw==,type:str]
            cpu: ENC[AES256_GCM,data:8tDgixI=,iv:mSk0K+ElTmJE6g4vTx9sj/EkYcy2ewYhVFK51KedfJo=,tag:LtFXAURkR2DiK/TKPNCLmw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t52j4y9qq32qnemahzvthge23mayrcfy3cjw9a8mrcw940vt6das0alrkz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWVduWTBsQUs5S2ppQWsw
            Q3I0WUNoVjgxSXFRcDA1VWtPaHVsZWt3UnhFClUwQlJRdm4rcVBmbzFZRVc2ZW5p
            YVJrcTg0dkY4Z0hzM09DNFo0UDVDZkEKLS0tIHNvbVVWTW1kaHlOejA4cy91aVlh
            d0Y2L1dvU25wcVBFWlFadGN3L0o4Z3cKETfMa+kYnd4P34epbv3hLmpH46P+Qyli
            iGfF/QRvbPYiOPXWro4mduzwzCf3ghxke0WLmn7IAmVgyi7rmwEvwQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1d8d79vsrf9h0avg3dwjl8fxsx3knzhvtg0ykf4k8w539878ql5zs53q6pj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4YnlFZFdLTXhaTlJjUWc3
            Y2tKWVZ3RXhZTk1yU3JmNnNmbm44SUtMR1dJCnR5TGhSU012TEFhSXUrQit0TjNL
            eTY5d1g0OUk2ak5uMklYaVNjUHp1WXcKLS0tIEcxN214SVQ0Zy92cVhnRVovYTZj
            c3pJQVpUMG44ZWk1c0JLTmEzclgyTGsKGQrQ/ntihQXZ3H53mOSfucDpiDI56Dk3
            b8FTn+gA+AkhCRgnjO/CEDZt5/8mBpKucRJE3EsX06CJ8mJZIi1++Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1a9fr72jum5ysrpfyw7z9fcp9dgfztd5wskmu4erj6e526ul334dq8clzec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTkRuRXhxT242Mm9OQTdG
            bHhNQ3Z1dEEwRVF0TmoxdkJDS1o0NmJZUWowCnR3eFhpTkhncWhQaUxnQi9DYi9B
            YWNBRDZFYnFuR1JpTUY3NnhWRm9GWm8KLS0tIG5HeEVwRlk5WVZER1JzaVlZa1RR
            MDNYdDBOWWEyZlJsUUlvNTVNdHplaUkK1zq8zMmz2coCgtwyQUALiA+jQcymrg2U
            x3kdyam1PtxtijK9xlWmFh2LZ93K1NOVXBeWrxni78Kcxi9ehSSfZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-23T16:47:43Z"
    mac: ENC[AES256_GCM,data:S/0/TY9Q8KB8ix0/2BD2YI2BnVZI2qUQuXjJsRQlb+SJbG9Ens1DkuCjUF/4tgZ+cnB28bk99ZFiZ54oh4eWXRUSqXJc5x88cpZ9mNyKTJfO9btHLLknstaFQFXyyLePNug/HEw0HcquZq13d+3m6tKR/IkqN6OfTLbUYOnOe3U=,iv:dqY28Hz7EsVyLaaOrwyQh1uB0j1OQgME1itfkj+IRO0=,tag:+Vu/z/7CEqZWx/ZmUO3+RQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
