empty: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t52j4y9qq32qnemahzvthge23mayrcfy3cjw9a8mrcw940vt6das0alrkz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXSW9ieEVibG9hQlRuK2Ri
            QVduZXRxcmtqeSsrVi82KzJnSkJkSnJBUHh3CjVSb2xPNlFrc3dPcDFhQy83b3FM
            eFNteWJ1QnEzSTJ2QTJDRHR0R0M4a28KLS0tIHFlU000R3RxUnN0MkxyclJ0M1Jq
            ZDRhZ0ZuRWsreWhXdnZ5TUxMVU5MSDAK8kSPgNdfWEFYfql46cKWe4Xi/SJRmDAH
            aNIrPpy3ui8ZVkTYAhsKkPi18zMEMHeDbv7mXHzMKEjQvcCb05aWxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-22T16:23:17Z"
    mac: ENC[AES256_GCM,data:2KZEtvqb5c1+WY0IQbG23PechzH+vLcbHtaZVnUlDR4O/FP0bHm7WOo1KBoK9U0qoc3d5l4slYsSnQtnQQtZZQ3KGJAGs6pjZ5GWN+5KsOzmTab4Dt9slJYhjtSDYmKqD79gpjvU1+ZA66lwvHnwGTRtqSlAKAe2F1deBwE9Utg=,iv:SmJxVyomRF5i/l5Yrt9VPiNV3ODPf9SXkLH+A0EFrbo=,tag:Nm6q+DGPDfsYyvu0H3tnpQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
