{{- range list "qcluster" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" (include "common.names.fullname" $) . }}
  labels:
    app.kubernetes.io/component: "{{ . }}"
spec:
  replicas: {{ $.Values.replicas.qcluster }}
  selector:
    matchLabels:
      app.kubernetes.io/component: "{{ . }}"
  template:
    metadata:
      labels:
        app.kubernetes.io/component: "{{ . }}"
        app.kubernetes.io/version: "{{ $.Values.image.tag }}"
    spec:
      {{- if $.Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml $.Values.image.pullSecrets | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      enableServiceLinks: true
      priorityClassName: {{ $.Values.priorityClassName }}
      containers:
        - name: {{ $.Chart.Name }}
          image: "{{ $.Values.image.repository }}/release-backend:{{ $.Values.image.tag }}"
          imagePullPolicy: "{{ $.Values.image.pullPolicy }}"
          args: ["/entrypoint.sh", "python3", "manage.py", "qcluster"]
          env:
            - name: "SENTRY_RELEASE"
              value: {{ $.Values.image.tag }}
            - name: "SERVICE"
              value: {{quote .}}
            {{- range $k, $v := $.Values.env }}
            - name: {{ quote $k }}
              value: {{ quote $v }}
            {{- end }}
            {{- range $name, $val := $.Values.envValueFrom }}
            - name: {{ $name }}
              valueFrom:
                {{- toYaml $val | nindent 16 }}
            {{- end }}
            {{- with $.Values.envFrom }}
          envFrom:
              {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            {{- with $.Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- with $.Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
