apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-frontend
  labels:
  {{- with .Values.service.frontend.annotations }}
  annotations:
  {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- $type := default "ClusterIP" .Values.service.frontend.type }}
  {{- if eq $type "ClusterIP" }}
  {{- with .Values.service.frontend.clusterIP }}
  clusterIP: {{ . }}
  {{ end }}
  {{- else if eq $type "LoadBalancer" }}
  {{- with .Values.service.frontend.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.service.frontend.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.frontend.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  type: {{ $type }}
  {{- if .Values.service.frontend.sessionAffinity }}
  sessionAffinity: {{ .Values.service.frontend.sessionAffinity }}
  {{- with .Values.service.frontend.sessionAffinityConfig }}
  sessionAffinityConfig:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- with .Values.service.frontend.externalIPs }}
  externalIPs:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.service.frontend.publishNotReadyAddresses }}
  publishNotReadyAddresses: {{ . }}
  {{- end }}
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: {{ .Values.service.frontend.name }}
      protocol: {{ .Values.service.frontend.protocol }}
      name: {{ .Values.service.frontend.name }}
      {{- if and (eq $type "NodePort") .Values.service.frontend.nodePort }}
      nodePort: {{ .Values.service.frontend.nodePort }}
  {{- end }}
  selector:
    app.kubernetes.io/component: "frontend"
