apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-backend
  labels:
  {{- with .Values.service.backend.annotations }}
  annotations:
  {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- $type := default "ClusterIP" .Values.service.backend.type }}
  {{- if eq $type "ClusterIP" }}
  {{- with .Values.service.backend.clusterIP }}
  clusterIP: {{ . }}
  {{ end }}
  {{- else if eq $type "LoadBalancer" }}
  {{- with .Values.service.backend.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.service.backend.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.backend.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  type: {{ $type }}
  {{- if .Values.service.backend.sessionAffinity }}
  sessionAffinity: {{ .Values.service.backend.sessionAffinity }}
  {{- with .Values.service.backend.sessionAffinityConfig }}
  sessionAffinityConfig:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- with .Values.service.backend.externalIPs }}
  externalIPs:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.service.backend.publishNotReadyAddresses }}
  publishNotReadyAddresses: {{ . }}
  {{- end }}
  ports:
    - port: 9100
      name: http-metrics
      protocol: TCP
      targetPort: http-metrics
    - port: {{ .Values.service.backend.port }}
      targetPort: {{ .Values.service.backend.name }}
      protocol: {{ .Values.service.backend.protocol }}
      name: {{ .Values.service.backend.name }}
      {{- if and (eq $type "NodePort") .Values.service.backend.nodePort }}
      nodePort: {{ .Values.service.backend.nodePort }}
  {{- end }}
  selector:
    app.kubernetes.io/component: "backend"
