# Generated by Django 4.2.7 on 2024-03-22 16:48

from django.db import migrations, models
import regenfrogs.utils.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=regenfrogs.utils.models._generate_medium_id,
                editable=False,
                max_length=32,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
