# Generated by Django 4.2.11 on 2024-03-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="farcaster_id",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
