# Generated by Django 4.2.11 on 2024-03-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_frameview"),
    ]

    operations = [
        migrations.RenameField(
            model_name="frameview",
            old_name="reply",
            new_name="interaction",
        ),
        migrations.AddField(
            model_name="frameview",
            name="cast_hash",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="frameview",
            name="cast_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="frameview",
            name="interactor_fid",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
