# Generated by Django 4.2.11 on 2024-03-23 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_rename_reply_frameview_interaction_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="frameview",
            name="interactor_fid",
        ),
    ]
