# Generated by Django 4.2.11 on 2024-03-23 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_frameview_interactor_fid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="frameview",
            name="valid",
        ),
    ]
