# Generated by Django 4.2.11 on 2024-03-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_frameview_valid"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="follower_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="following_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
