# Generated by Django 4.2.11 on 2024-03-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_user_verified_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="frameview",
            name="cast_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
