# Generated by Django 4.2.11 on 2024-03-22 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import regenfrogs.utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FrogImage",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=regenfrogs.utils.models._generate_medium_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("prompt", models.TextField()),
                ("reply", models.JSONField(blank=True, null=True)),
                ("remote_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "generation_status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("pending", "Pending"),
                            ("in-progress", "In Progress"),
                            ("ready", "Ready"),
                        ],
                        default="waiting",
                        max_length=255,
                    ),
                ),
                ("status_response", models.JSONField(blank=True, null=True)),
                ("waiting_since", models.DateTimeField(blank=True, null=True)),
                ("waiting_until", models.DateTimeField(blank=True, null=True)),
                ("requested_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("image_chosen", models.PositiveIntegerField(blank=True, null=True)),
                ("image_1", models.ImageField(blank=True, null=True, upload_to="images/")),
                ("image_2", models.ImageField(blank=True, null=True, upload_to="images/")),
                ("image_3", models.ImageField(blank=True, null=True, upload_to="images/")),
                ("image_4", models.ImageField(blank=True, null=True, upload_to="images/")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Frog",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=regenfrogs.utils.models._generate_medium_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "image",
                    models.OneToOneField(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="frogs.frogimage"
                    ),
                ),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ("-updated_at", "-created_at"),
                "abstract": False,
            },
        ),
    ]
