# Generated by Django 4.2.11 on 2024-03-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="frogimage",
            name="references",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
