# Generated by Django 4.2.11 on 2024-03-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frogs", "0002_frogimage_references"),
    ]

    operations = [
        migrations.AddField(
            model_name="frogimage",
            name="ipfs_hash",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
