# Generated by Django 4.2.11 on 2024-03-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frogs", "0003_frogimage_ipfs_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="frogimage",
            name="generation_status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting"),
                    ("pending", "Pending"),
                    ("in-progress", "In Progress"),
                    ("failed", "Failed"),
                    ("completed", "Completed"),
                ],
                default="waiting",
                max_length=255,
            ),
        ),
    ]
