# Generated by Django 4.2.11 on 2024-03-22 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("frogs", "0005_frogstyle_frogstyleimagereference_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="frogimage",
            name="style",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outputs",
                to="frogs.frogstyle",
            ),
        ),
        migrations.DeleteModel(
            name="FrogStyleImageOutput",
        ),
    ]
