# Generated by Django 4.2.11 on 2024-03-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frogs", "0006_frogimage_style_delete_frogstyleimageoutput"),
    ]

    operations = [
        migrations.AddField(
            model_name="frogstyle",
            name="prompt_prefix",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
