# Generated by Django 4.2.11 on 2024-03-23 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("frogs", "0009_alter_frogimage_options_frogimage_vectorized_svg"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="frogimage",
            name="vectorized_svg",
        ),
    ]
