# Generated by Django 4.2.11 on 2024-03-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frogs", "0011_froglog_frogprofile_delete_frog_froglog_frog"),
    ]

    operations = [
        migrations.AddField(
            model_name="frogprofile",
            name="ipfs_image_cid",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="frogprofile",
            name="ipfs_metadata_cid",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="frogprofile",
            name="minted_nft_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="frogprofile",
            name="minted_nft_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="frogprofile",
            name="minted_nft_receipt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="frogprofile",
            name="minted_nft_tx_hash",
            field=models.TextField(blank=True, null=True),
        ),
    ]
