# Generated by Django 4.2.11 on 2024-03-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frogs", "0012_frogprofile_ipfs_image_cid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="frogprofile",
            name="last_loop",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="frogprofile",
            name="next_loop",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
