# Generated by Django 4.2.11 on 2024-03-23 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("frogs", "0014_frogprofile_died_at_alter_frogprofile_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="froglog",
            name="created_by",
        ),
        migrations.AddField(
            model_name="froglog",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
