# Generated by Django 4.2.11 on 2024-03-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frogs", "0015_remove_froglog_created_by_froglog_actor"),
    ]

    operations = [
        migrations.AddField(
            model_name="frogprofile",
            name="sanity_counter",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
