# Generated by Django 4.2.11 on 2024-03-24 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("frogs", "0017_rename_ipfs_image_cid_frogprofile_ipfs_image_hash"),
    ]

    operations = [
        migrations.RenameField(
            model_name="frogprofile",
            old_name="ipfs_image_hash",
            new_name="ipfs_metadata_hash",
        ),
        migrations.RemoveField(
            model_name="frogprofile",
            name="ipfs_metadata_cid",
        ),
    ]
