apiVersion: ENC[AES256_GCM,data:2n8=,iv:ROBZVUZ9c7bP9SO0VewM2lTO7b0x5Vm8ztFrg48jj0k=,tag:6+agxtXiq03MwiRWS9bOBg==,type:str]
data:
    .dockerconfigjson: ENC[AES256_GCM,data:hRYckCjvhNnkhWzGJ39UvYf1LN3YAwqZQJCRilMN7xYVPz3cxLmr4Wcu4Cb7SnmfjQ4MfMaCDtWmObLoevChn978bWNwD8/+pQBMEYTpzHi3DutKOobkLfCIZgBbfFaPIyCwiSqy4xNxupDhdGZXQJXfOs692OIztdbNybNBDeuGPX4rdAngNoFLvlY1WmILIGfT6xU52NqMf+nC,iv:Q6BhJ8gFf4RyqATZ30lkMd5MiMtB+5L820SwUfrAXZ4=,tag:9c+BiFr+FTo2dLDyGorJ/g==,type:str]
kind: ENC[AES256_GCM,data:6HvcmVvj,iv:8mxRwh07TIx0jeQNrLw+iHcF3ZhztBMfaW4UcgdivaI=,tag:2Vo49MIAvQMgfRQYXjYvZg==,type:str]
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:s4L8ejt0+TIvQzUlpBDzU1gs,iv:fYBkgctBWNUhys7M29PHL2htA/wdQJ1MRFzfroxmznU=,tag:jVPzkHMmwKKLTvLUjJ56kg==,type:str]
type: ENC[AES256_GCM,data:mQWrd9Pg/JqvHQ5zoXE5Y+Tye9Mrb8t8WJ5ZWlw1,iv:BaLuoU+7vWICjMfn76dqBuPwhyKt5bT7ezdQQBCv0bU=,tag:Ehqg3s6+ZTksnlzeU/A3gA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t52j4y9qq32qnemahzvthge23mayrcfy3cjw9a8mrcw940vt6das0alrkz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdlY3dzE4N1hkUytibnow
            cWV0ZmY5N0JLbi9ONzk4aEp5WkxBL1BsM0ZjCnNxSjdNcWxXdEFvcUVFOWNxSGo4
            YUZTcHVlMHUvb2NGV1BLNTc4S1RmRUEKLS0tIDA2Nm9uR3dDSHhWVmlUbkN1Y09Z
            UzhyTXRtZU9HalBUL2dzd1liSVVvRWsKIaCc8mFIjyWPuLshOIEU2UB6bXo+v0vt
            mYjYDTVZwMiv9ZMYYWpIGunooyDW0kw7/6ut/pOFOb5wCw8pLJy5Bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-22T16:23:13Z"
    mac: ENC[AES256_GCM,data:Dnsl8VvKyZspxj0O8/O3qrqagAhIn7p6OagJCCChoHsEN1H47koH/ojR/MXZ/zj5jOtoB9UYzodggayUxQiAwMjtBoe4VV5G1ZqdYRsFjgUtN7qfNpU/MmYP6DxgH7+jO2R0nEfwk7Dq988cANDzo2M3NBN7jyI1uT4Wu7JQevo=,iv:CBn0qaO2XuPY9FG80kFLgPMd0ytFVFCu/bhU2zU+K68=,tag:WgOueguyV/pJDBpZpMVuOg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
