SPECIES = [
    "Green tree frog - Bright green with darker green spots or stripes",
    "Red-eyed tree frog - Bright green with blue and yellow markings and red eyes",
    "Poison dart frog - Brightly colored with bold patterns like stripes, spots, or bands in combinations of black, blue, orange, or yellow",
    "Dumpy tree frog - Light green or grayish-green with smooth skin",
    "African clawed frog - Olive green or brown with smooth skin",
    "White's tree frog - Light green with creamy white or yellow spots",
    "Amazon milk frog - Light green with creamy white or yellow markings and black spots",
    "Tomato frog - Bright red-orange with smooth skin",
    "Fire-bellied toad - Bright green with black and red markings on the underside",
    "Vietnamese mossy frog - Green or brown with rough, moss-like texture on the skin",
    "Marbled reed frog - Green or brown with marbled patterns of darker colors",
    "Budgett's frog - Green or brown with a large, rounded body and smooth skin",
    "Australian green tree frog - Bright green with smooth skin",
    "Cuban tree frog - Green or brown with bumpy skin",
    "Malayan horned frog - Green or brown with spiky protrusions on the skin",
    "Yellow-bellied toad - Olive green with yellow or orange markings on the underside",
    "Oriental fire-bellied toad - Bright green with black and red markings on the underside",
    "Black-spotted casque-headed tree frog - Green with black spots and a bumpy casque on the head",
    "Golden poison frog - Bright yellow or orange with black spots or bands",
    "Bumblebee poison frog - Black with bright yellow stripes or bands",
    "Blue poison dart frog - Bright blue with black markings",
    "Green and black poison dart frog - Bright green with black spots or stripes",
    "Yellow-banded poison dart frog - Bright yellow with black bands",
    "Splendid leaf frog - Green with white or yellow markings and red eyes",
    "Green-eyed tree frog - Bright green with large, striking green eyes",
    "Southern leopard frog - Green or brown with darker spots or blotches",
    "Pickerel frog - Green or brown with rectangular spots along the back",
    "American bullfrog - Green or brown with a large, rounded body",
    "Northern leopard frog - Green or brown with circular spots along the back",
    "Wood frog - Brown or tan with darker markings resembling a mask across the eyes",
]

HANDS = [
    "tiny umbrella",
    "flower bouquet",
    "lollipop",
    "tiny book",
    "paintbrush and palette",
    "cup of tea",
    "fishing rod with a tiny fish",
    "camera",
    "heart-shaped balloon",
    "basket of mushrooms",
    "slice of pizza",
    "magic wand",
    "jar of fireflies",
    "musical instrument like a flute or a ukulele",
    "smartphone",
    "slice of watermelon",
    "treasure map",
    "stack of pancakes",
    "magnifying glass",
    "bag of popcorn",
    "snow globe",
    "kite",
    "telescope",
    "skateboard",
    "bunch of balloons",
    "cookie",
    "bouquet of balloons",
    "potted plant",
    "letter with a wax seal",
    "small toy frog",
]

CLOTHES = [
    "tiny bow tie",
    "oversized glasses",
    "flower crown",
    "polka dot scarf",
    "top hat",
    "bandana around its neck",
    "sweater with a heart patch",
    "Hawaiian shirt",
    "superhero cape",
    "tutu",
    "monocle",
    "striped beanie",
    "t-shirt with a funny slogan",
    "cozy knitted sweater",
    "denim jacket",
    "cowboy hat",
    "lei necklace",
    "chef's hat and apron",
    "wizard's robe and hat",
    "sports jersey",
    "hoodie with ears",
    "backpack",
    "pair of roller skates",
    "snorkel and goggles",
    "graduation cap",
    "crown made of leaves",
    "detective's magnifying glass",
    "pair of rain boots",
    "fairy wings",
    "pirate's hat and eyepatch",
]
