SPECIES = [
    "Green tree frog - Bright green with darker green spots or stripes",
    "Red-eyed tree frog - Bright green with blue and yellow markings and red eyes",
    "Poison dart frog - Brightly colored with bold patterns like stripes, spots, or bands in combinations of black, blue, orange, or yellow",
    "Dumpy tree frog - Light green or grayish-green with smooth skin",
    "African clawed frog - Olive green or brown with smooth skin",
    "White's tree frog - Light green with creamy white or yellow spots",
    "Amazon milk frog - Light green with creamy white or yellow markings and black spots",
    "Tomato frog - Bright red-orange with smooth skin",
    "Fire-bellied toad - Bright green with black and red markings on the underside",
    "Vietnamese mossy frog - Green or brown with rough, moss-like texture on the skin",
    "Marbled reed frog - Green or brown with marbled patterns of darker colors",
    "Budgett's frog - Green or brown with a large, rounded body and smooth skin",
    "Australian green tree frog - Bright green with smooth skin",
    "Cuban tree frog - Green or brown with bumpy skin",
    "Malayan horned frog - Green or brown with spiky protrusions on the skin",
    "Yellow-bellied toad - Olive green with yellow or orange markings on the underside",
    "Oriental fire-bellied toad - Bright green with black and red markings on the underside",
    "Black-spotted casque-headed tree frog - Green with black spots and a bumpy casque on the head",
    "Golden poison frog - Bright yellow or orange with black spots or bands",
    "Bumblebee poison frog - Black with bright yellow stripes or bands",
    "Blue poison dart frog - Bright blue with black markings",
    "Green and black poison dart frog - Bright green with black spots or stripes",
    "Yellow-banded poison dart frog - Bright yellow with black bands",
    "Splendid leaf frog - Green with white or yellow markings and red eyes",
    "Green-eyed tree frog - Bright green with large, striking green eyes",
    "Southern leopard frog - Green or brown with darker spots or blotches",
    "Pickerel frog - Green or brown with rectangular spots along the back",
    "American bullfrog - Green or brown with a large, rounded body",
    "Northern leopard frog - Green or brown with circular spots along the back",
    "Wood frog - Brown or tan with darker markings resembling a mask across the eyes",
    "Sapphire-eyed tree frog - Bright green with shimmering sapphire-blue eyes",
    "Celestial star frog - Dark blue with tiny glowing star-like patterns scattered across its body",
    "Rainbow-striped dart frog - Vibrantly colored with rainbow stripes running along its back",
    "Crystal-clear glass frog - Transparent with visible internal organs and delicate veins",
    "Moonlit pond frog - Silver-gray with luminescent patches resembling moonlight reflections",
    "Coral reef frog - Neon pink with intricate patterns resembling coral reefs and tropical fish",
    "Frosty tundra frog - Pale blue with frosty white markings and icicle-shaped protrusions",
    "Sunburst frog - Bright yellow with fiery orange and red patterns radiating from its body",
    "Twilight mist frog - Muted lavender with swirling mist-like patterns and glowing eyes",
    "Midnight rainforest frog - Deep purple with iridescent green and blue markings reminiscent of a lush rainforest at night",
    "Aurora borealis frog - Shimmering shades of green, purple, and blue with aurora-like patterns across its body",
    "Solar flare frog - Fiery orange with sunburst patterns and glowing red eyes",
    "Cosmic dust frog - Speckled with glittering stardust and adorned with celestial symbols",
    "Enchanted forest frog - Mossy green with shimmering golden flecks and tiny woodland creatures hiding in its patterns",
    "Firefly glow frog - Luminescent green with glowing spots resembling fireflies on a summer night",
    "Ocean wave frog - Aqua blue with swirling patterns resembling ocean waves and sea foam",
    "Rainbow prism frog - Transparent with rainbow-colored refractions casting colorful patterns around it",
    "Desert oasis frog - Sand-colored with vibrant oasis plants and crystal-clear water droplets on its skin",
    "Thunderstorm frog - Slate gray with jagged lightning-like patterns and rumbling thundercloud markings",
    "Aurora Australis frog - Iridescent shades of pink, purple, and green with shimmering patterns reminiscent of the Southern Lights",
    "Green Tree Frog - Bright lime green with darker green blotches or stripes, large toe pads, and golden eyes.",
    "Red-Eyed Tree Frog - Bright green with blue and yellow markings, striking red eyes with vertical pupil slits.",
    "Poison Dart Frog (Dendrobates tinctorius) - Boldly colored in patterns of black, yellow, orange, and blue. Some morphs are solid bright colors.",
    "Whites Tree Frog - Green or gray with bright blue and yellow striping on sides and limbs. Large toe pads.",
    "Wallace's Flying Frog - Mottled brown and green, large webbed feet allow gliding, orange throat sac.",
    "Waxy Monkey Frog - Bright green with yellow and black markings, disk-like toepads, males have humped backs.",
    "Vietnamese Mossy Frog - Mossy green with flattened body, looks just like a clump of moss or lichen.",
    "Red Rain Frog - Cherry red with black markings and yellowish orange feet and underbelly.",
    "Amazon Milk Frog - Dull green or brown with orange or red spots and stripes, milky white underbelly.",
    "Glass Frog - Translucent lime green skin reveals internal organs, bulging white eyes.",
    "Red-Legged Banana Frog - Mustard yellow with reddish-orange blotches and legs, inflatable vocal sacs.",
    "Argentine Horned Frog - Rotund with conical horn over each eye, brown with orange mottling.",
    "Phantasmal Poison Frog - Jet black with neon yellow spots and stripes, one of the most toxic frogs.",
    "Bumblebee Toad - Yellow and black striped or spotted pattern like a bumblebee's markings.",
    "Tomato Frog - Bright red all over like a ripe tomato, native to Madagascar's rain forests.",
    "Clown Frog - Black with white stripes around mouth giving a clown-like grinning appearance.",
    "Budgett's Frog - Olive drab with irregular orange and black spots, horizontal pupils.",
    "Pacman Frog - Named for its round body shape and enormous mouth, mottled green and brown.",
    "Mexican Burrowing Toad - Pudgy with short limbs and a 'smiley face' marking on its belly.",
    "Painted Reed Frog - Vivid green with red, blue or yellow racing stripes down the sides.",
    "Golden Mantella - Brilliant golden-yellow with scattered black spots, one of the most iconic frogs of Madagascar.",
    "Strawberry Poison-Dart Frog - Strawberry red with distinctive navy blue speckling all over its body.",
    "Lémur Leaf Frog - Perfectly camouflaged bright green with reddish-orange eyes and yellow hands/feet.",
    "Tiger Frog - Yellow or green with striking black tiger-like stripes and blotches all over.",
    "Yellow Terribile Leaf Frog - Bright yellow with a few darker blotches, perfectly mimicking a new leaf.",
    "Paradoxical Frog - Mottled browns and grays with bright red/orange flash markings when disturbed.",
    "Pickerel Frog - Large and stocky with distinct square shape, tan to olive with bright yellow groin patch.",
    "Vietnamese Mossy Frog - Looking just like a mossy rock, with flattened body and fringed toes.",
    "Bornean Flat-headed Frog - Distinctively broad, flat head and mottled olive green and brown camouflage.",
    "African Dwarf Frog - Plump body, surprisingly round eyes, pale green or brown with darker splotches.",
    "Fire-Bellied Toad - Brightly patterned black and green toad with vivid red/orange underside.",
    "Harlequin Frog - Boldly striped and spotted in black and orange or red, like a harlequin costume.",
    "Yellow Rain Frog - Bright lemon yellow with darker blotches, long legs and horizontal pupils.",
    "Purple Frog - Rich deep purple coloration all over the body, found in India's Western Ghats.",
    "Tungara Frog - Small but boldly patterned, tan with dark chevron patterns and wavy yellow stripes.",
    "Common Parsley Frog - Emerald green with darker irregular wavy lines, excellent camouflage in foliage.",
    "Red-Legged Frog - Golden brown with distinctive cherry red legs and underbelly.",
    "Blue Poison Frog - Indigo blue body with jet black markings, one of the most toxic species.",
    "Green-and-Black Poison Dart Frog - Vivid leaf green with thick black spotting and striping all over.",
    "Mimic Poison Frog - Orange head and limbs with blue-black body, mimicking other toxic species.",
    "Panamanian Golden Frog - Beautifully patterned in black and brilliant golden yellow.",
    "Black Rain Frog - Jet black with bright yellow or orange feet and markings. Native to Brazil.",
    "Blue Monkey Frog - Sky blue body with darker turquoise blotches and golden eyes. From Tanzania.",
    "Cascade Frog - Bright green with reddish warts and stripes. Found in the Pacific Northwest.",
    "Mission Golden-eyed Frog - Olive green with striking golden eyes and orange groin. From Costa Rica.",
    "Raccoon Frog - Black mask-like markings around the eyes make it look like a raccoon.",
    "Climbing Pandangan Frog - Mossy green with bright red/orange eyes. Excellent climber.",
    "Malaysian Sticky Frog - Warty emerald green with sticky toe pads for climbing slick surfaces.",
    "Javan Gliding Frog - Mottled grays with huge webbed feet and flaps for gliding between trees.",
    "Sambava Tomato Frog - Deep red all over like a ripe tomato with darker red markings.",
    "Chubby Frog - Aptly named for its extremely rounded body and pudgy appearance.",
    "Wood Frog - Warm reddish-brown with a distinctive dark eye mask. Found in eastern North America.",
    "Solomon Island Leaf Frog - Perfectly leaf-shaped and colored an incredible bright green.",
    "Yunan Club-tailed Frog - Bizarre species with a thick 'club' tail appendage longer than its body.",
    "Betic Midwife Toad - Warty brown and gray with bright red belly. Males carry eggs on their backs.",
    "Cricket Frog - Small frog with warty skin and distinctive crossed markings on its back.",
    "Sea Frog - Exceptional frog found along tropical beaches, sandy brown with dark splotches.",
    "Foothill Yellow-legged Frog - Reddish brown or gray-green with sports of yellow on groin and legs.",
    "Yellow-banded Poison Frog - Velvety black body with distinctive bright yellow band around the middle.",
    "Fleischmann's Glass Frog - Translucent lime green skin reveals internal organs, found in rainforests.",
    "Parson's Chameleon Frog - Incredibly well-camouflaged, changing colors and textures to match surroundings.",
    "Dog's Ground Frog - Robust frog with brown camo and distinctive white-tipped snout.",
    "Marsupial Frog - Unique pouch on the female's back to carry eggs and tadpoles. Green and brown.",
    "Indian Golden Frog - Striking metallic golden-yellow coloring all over its plump body.",
    "Urania's Poison-Dart Frog - Bright royal blue body with thick black spots and yellow racing stripes.",
    "Missing Femur Frog - Named for its lack of femur bones, giving its legs a splayed appearance.",
    "Spotted Rain Frog - Yellow, orange or red with irregular black spots and blotches all over.",
    "Rusty's Robber Frog - Stout frog with powerful jaws, brick red with darker spots and bars.",
    "Waxy Monkey Tree Frog - Bright leaf green with irregular yellow spots and markings.",
    "Annam Flying Frog - Mottled grays and browns with hugely webbed feet for impressive gliding.",
    "Chiricahua Leopard Frog - Olive green with distinctive leopard-like spots and blotches.",
    "Long-Nose Horned Frog - With an enormous protruding snout and horn over each eye, camouflaged brown.",
    "Desert Rain Frog - Tan, mottled brown and pink like the desert sands it lives in.",

]

HANDS = [
    "tiny umbrella",
    "flower bouquet",
    "lollipop",
    "tiny book",
    "paintbrush and palette",
    "cup of tea",
    "fishing rod with a tiny fish",
    "camera",
    "heart-shaped balloon",
    "basket of mushrooms",
    "slice of pizza",
    "magic wand",
    "jar of fireflies",
    "musical instrument like a flute or a ukulele",
    "smartphone",
    "slice of watermelon",
    "treasure map",
    "stack of pancakes",
    "magnifying glass",
    "bag of popcorn",
    "snow globe",
    "kite",
    "telescope",
    "skateboard",
    "bunch of balloons",
    "cookie",
    "bouquet of balloons",
    "potted plant",
    "letter with a wax seal",
    "small toy frog",
    "ice cream cone",
    "rainbow-colored kite",
    "teddy bear",
    "musical note sheet",
    "bubble wand",
    "basket of freshly baked cookies",
    "fairy wand",
    "vintage compass",
    "treasure chest overflowing with gems",
    "enchanted crystal ball",
    "bunch of helium balloons shaped like animals",
    "pencil and sketchbook",
    "adventure map with landmarks",
    "dragon egg",
    "tiny watering can for plants",
    "golden key to a secret garden",
    "basket of colorful Easter eggs",
    "cupcake with rainbow frosting",
    "time-traveling hourglass",
    "bouquet of magical flowers",
    "glow-in-the-dark star wand",
    "potion bottle with swirling colors",
    "exotic fruit from a faraway land",
    "telescope with a whimsical design",
    "chest filled with magical artifacts",
    "bubble tea with tapioca pearls",
    "crystal wand with sparkling crystals",
    "cosmic telescope for stargazing",
    "spellbook with ancient runes",
    "origami animals folded with care",
    "feather quill and ink bottle",
    "basket of freshly picked strawberries",
    "fairy dust in a glass jar",
    "rainbow-colored ribbon streamers",
    "giant fluffy cloud pillow",
    "bonsai tree in a miniature pot",
    "dragonfly perched on a leaf",
    "fairy tale book with a worn cover",
]

CLOTHES = [
    "tiny bow tie",
    "oversized glasses",
    "flower crown",
    "polka dot scarf",
    "top hat",
    "bandana around its neck",
    "sweater with a heart patch",
    "Hawaiian shirt",
    "superhero cape",
    "tutu",
    "monocle",
    "striped beanie",
    "t-shirt with a funny slogan",
    "cozy knitted sweater",
    "denim jacket",
    "cowboy hat",
    "lei necklace",
    "chef's hat and apron",
    "wizard's robe and hat",
    "sports jersey",
    "hoodie with ears",
    "backpack",
    "pair of roller skates",
    "snorkel and goggles",
    "graduation cap",
    "crown made of leaves",
    "detective's magnifying glass",
    "pair of rain boots",
    "fairy wings",
    "pirate's hat and eyepatch",
    "sun hat with a flower",
    "raincoat and rain boots",
    "backpack filled with supplies",
    "bow tie made of leaves",
    "flower necklace",
    "pair of goggles for swimming",
    "knitted scarf and mittens",
    "wristwatch",
    "necklace with a pendant shaped like a lily pad",
    "belt with a tiny pouch attached",
    "explorer's vest with pockets",
    "crown made of twigs and flowers",
    "ribbon tied around one leg",
    "sash with a medal",
    "wristband with a charm",
    "anklet with bells",
    "badge pinned to its chest",
    "locket around its neck",
    "friendship bracelet",
    "tiny cape",
]

DEATH_REASONS = [
    "Accidentally overdosed on virtual caffeine after drinking too many digital energy drinks",
    "Got caught up in a heated debate with a virtual fly and forgot to eat",
    "Attempted a daring escape from its virtual terrarium and got lost in the digital jungle",
    "Fell victim to a virtual reality glitch that turned its surroundings into a pixelated mess",
    "Engaged in a virtual rap battle with a rival frog and lost its voice from all the croaking",
    "Tried to impress a virtual frog date with a risky skydiving stunt and landed on a pixelated cactus",
    "Developed a sudden obsession with playing virtual video games and forgot to eat",
    "Got into a virtual food fight with a group of mischievous digital squirrels and lost",
    "Accidentally activated a self-destruct button while trying to unlock a secret level in its virtual habitat",
    "Attempted to reenact scenes from a virtual action movie and ended up in a pixelated explosion",
    "Fell asleep while binging on virtual reality TV and forgot to wake up for dinner",
    "Engaged in a virtual dance-off with a rival frog and tripped over its own virtual feet",
    "Tried to impress its virtual friends by attempting a dangerous stunt jump and landed in a virtual pond without water",
    "Mistook a virtual hot dog for a virtual snake and attempted to eat it",
    "Got distracted by a virtual rainbow and accidentally hopped off a virtual cliff",
    "Developed a case of virtual stage fright during a virtual talent show and froze on stage",
    "Attempted to prank its virtual owner by hiding in a virtual freezer and got frostbite",
    "Got carried away while practicing its virtual yoga moves and twisted itself into a digital knot",
    "Became a virtual superhero for a day and attempted to fly off a virtual building",
    "Tried to break a virtual world record for the longest virtual hop and ran out of virtual energy halfway through",
    "Developed a virtual addiction to playing virtual reality games and forgot to eat or sleep",
    "Participated in a virtual cooking competition and accidentally ate its own virtual dish, which turned out to be toxic",
    "Attempted to imitate a virtual ninja and got tangled in its own virtual ninja robe",
    "Joined a virtual frog choir and croaked so loudly that it shattered its own virtual eardrums",
    "Tried to impress its virtual crush by attempting a virtual magic trick and accidentally made itself disappear",
    "Accepted a virtual dare to eat a virtual spicy pepper and suffered from a virtual case of indigestion",
    "Fell victim to a virtual prank involving a virtual catapult and a virtual bucket of virtual water",
    "Attempted to break the virtual world record for the longest virtual jump and overshot its landing, crashing into a virtual wall",
    "Got into a virtual paintball battle with a group of virtual frogs and accidentally swallowed a virtual paintball",
    "Became addicted to virtual reality shopping and spent all its virtual currency on virtual luxury items, forgetting to buy food",
]
