SPECIES = [
    "Green tree frog - Bright green with darker green spots or stripes",
    "Red-eyed tree frog - Bright green with blue and yellow markings and red eyes",
    "Poison dart frog - Brightly colored with bold patterns like stripes, spots, or bands in combinations of black, blue, orange, or yellow",
    "Dumpy tree frog - Light green or grayish-green with smooth skin",
    "African clawed frog - Olive green or brown with smooth skin",
    "White's tree frog - Light green with creamy white or yellow spots",
    "Amazon milk frog - Light green with creamy white or yellow markings and black spots",
    "Tomato frog - Bright red-orange with smooth skin",
    "Fire-bellied toad - Bright green with black and red markings on the underside",
    "Vietnamese mossy frog - Green or brown with rough, moss-like texture on the skin",
    "Marbled reed frog - Green or brown with marbled patterns of darker colors",
    "Budgett's frog - Green or brown with a large, rounded body and smooth skin",
    "Australian green tree frog - Bright green with smooth skin",
    "Cuban tree frog - Green or brown with bumpy skin",
    "Malayan horned frog - Green or brown with spiky protrusions on the skin",
    "Yellow-bellied toad - Olive green with yellow or orange markings on the underside",
    "Oriental fire-bellied toad - Bright green with black and red markings on the underside",
    "Black-spotted casque-headed tree frog - Green with black spots and a bumpy casque on the head",
    "Golden poison frog - Bright yellow or orange with black spots or bands",
    "Bumblebee poison frog - Black with bright yellow stripes or bands",
    "Blue poison dart frog - Bright blue with black markings",
    "Green and black poison dart frog - Bright green with black spots or stripes",
    "Yellow-banded poison dart frog - Bright yellow with black bands",
    "Splendid leaf frog - Green with white or yellow markings and red eyes",
    "Green-eyed tree frog - Bright green with large, striking green eyes",
    "Southern leopard frog - Green or brown with darker spots or blotches",
    "Pickerel frog - Green or brown with rectangular spots along the back",
    "American bullfrog - Green or brown with a large, rounded body",
    "Northern leopard frog - Green or brown with circular spots along the back",
    "Wood frog - Brown or tan with darker markings resembling a mask across the eyes",
    "Sapphire-eyed tree frog - Bright green with shimmering sapphire-blue eyes",
    "Celestial star frog - Dark blue with tiny glowing star-like patterns scattered across its body",
    "Rainbow-striped dart frog - Vibrantly colored with rainbow stripes running along its back",
    "Crystal-clear glass frog - Transparent with visible internal organs and delicate veins",
    "Moonlit pond frog - Silver-gray with luminescent patches resembling moonlight reflections",
    "Coral reef frog - Neon pink with intricate patterns resembling coral reefs and tropical fish",
    "Frosty tundra frog - Pale blue with frosty white markings and icicle-shaped protrusions",
    "Sunburst frog - Bright yellow with fiery orange and red patterns radiating from its body",
    "Twilight mist frog - Muted lavender with swirling mist-like patterns and glowing eyes",
    "Midnight rainforest frog - Deep purple with iridescent green and blue markings reminiscent of a lush rainforest at night",
    "Aurora borealis frog - Shimmering shades of green, purple, and blue with aurora-like patterns across its body",
    "Solar flare frog - Fiery orange with sunburst patterns and glowing red eyes",
    "Cosmic dust frog - Speckled with glittering stardust and adorned with celestial symbols",
    "Enchanted forest frog - Mossy green with shimmering golden flecks and tiny woodland creatures hiding in its patterns",
    "Firefly glow frog - Luminescent green with glowing spots resembling fireflies on a summer night",
    "Ocean wave frog - Aqua blue with swirling patterns resembling ocean waves and sea foam",
    "Rainbow prism frog - Transparent with rainbow-colored refractions casting colorful patterns around it",
    "Desert oasis frog - Sand-colored with vibrant oasis plants and crystal-clear water droplets on its skin",
    "Thunderstorm frog - Slate gray with jagged lightning-like patterns and rumbling thundercloud markings",
    "Aurora Australis frog - Iridescent shades of pink, purple, and green with shimmering patterns reminiscent of the Southern Lights",
]

HANDS = [
    "tiny umbrella",
    "flower bouquet",
    "lollipop",
    "tiny book",
    "paintbrush and palette",
    "cup of tea",
    "fishing rod with a tiny fish",
    "camera",
    "heart-shaped balloon",
    "basket of mushrooms",
    "slice of pizza",
    "magic wand",
    "jar of fireflies",
    "musical instrument like a flute or a ukulele",
    "smartphone",
    "slice of watermelon",
    "treasure map",
    "stack of pancakes",
    "magnifying glass",
    "bag of popcorn",
    "snow globe",
    "kite",
    "telescope",
    "skateboard",
    "bunch of balloons",
    "cookie",
    "bouquet of balloons",
    "potted plant",
    "letter with a wax seal",
    "small toy frog",
    "ice cream cone",
    "rainbow-colored kite",
    "teddy bear",
    "musical note sheet",
    "bubble wand",
    "basket of freshly baked cookies",
    "fairy wand",
    "vintage compass",
    "treasure chest overflowing with gems",
    "enchanted crystal ball",
    "bunch of helium balloons shaped like animals",
    "pencil and sketchbook",
    "adventure map with landmarks",
    "dragon egg",
    "tiny watering can for plants",
    "golden key to a secret garden",
    "basket of colorful Easter eggs",
    "cupcake with rainbow frosting",
    "time-traveling hourglass",
    "bouquet of magical flowers",
    "glow-in-the-dark star wand",
    "potion bottle with swirling colors",
    "exotic fruit from a faraway land",
    "telescope with a whimsical design",
    "chest filled with magical artifacts",
    "bubble tea with tapioca pearls",
    "crystal wand with sparkling crystals",
    "cosmic telescope for stargazing",
    "spellbook with ancient runes",
    "origami animals folded with care",
    "feather quill and ink bottle",
    "basket of freshly picked strawberries",
    "fairy dust in a glass jar",
    "rainbow-colored ribbon streamers",
    "giant fluffy cloud pillow",
    "bonsai tree in a miniature pot",
    "dragonfly perched on a leaf",
    "fairy tale book with a worn cover",
]

CLOTHES = [
    "tiny bow tie",
    "oversized glasses",
    "flower crown",
    "polka dot scarf",
    "top hat",
    "bandana around its neck",
    "sweater with a heart patch",
    "Hawaiian shirt",
    "superhero cape",
    "tutu",
    "monocle",
    "striped beanie",
    "t-shirt with a funny slogan",
    "cozy knitted sweater",
    "denim jacket",
    "cowboy hat",
    "lei necklace",
    "chef's hat and apron",
    "wizard's robe and hat",
    "sports jersey",
    "hoodie with ears",
    "backpack",
    "pair of roller skates",
    "snorkel and goggles",
    "graduation cap",
    "crown made of leaves",
    "detective's magnifying glass",
    "pair of rain boots",
    "fairy wings",
    "pirate's hat and eyepatch",
    "sun hat with a flower",
    "raincoat and rain boots",
    "backpack filled with supplies",
    "bow tie made of leaves",
    "flower necklace",
    "pair of goggles for swimming",
    "knitted scarf and mittens",
    "wristwatch",
    "necklace with a pendant shaped like a lily pad",
    "belt with a tiny pouch attached",
    "explorer's vest with pockets",
    "crown made of twigs and flowers",
    "ribbon tied around one leg",
    "sash with a medal",
    "wristband with a charm",
    "anklet with bells",
    "badge pinned to its chest",
    "locket around its neck",
    "friendship bracelet",
    "tiny cape",
]
